services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tfe_cycling
      POSTGRES_USER: tfe_user
      POSTGRES_PASSWORD: ${PGPASSWORD:-}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DB/sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./DB/sql/remplissage.sql:/docker-entrypoint-initdb.d/02-remplissage.sql:ro

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tfe_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-tfe_user}:${POSTGRES_PASSWORD:-change_me}@postgres:5432/${POSTGRES_DB:-tfe_cycling}
      PGHOST: postgres
      PGPORT: ${PGPORT:-5432}
      PGDATABASE: ${PGDATABASE:-tfe_cycling}
      PGUSER: ${PGUSER:-tfe_user}
      PGPASSWORD: ${POSTGRES_PASSWORD:-change_me}
      APP_FERNET_KEY: ${APP_FERNET_KEY:-}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-}
      JWT_ALGORITHM: ${JWT_ALGORITHM:-}
      JWT_EXPIRE_MINUTES: ${JWT_EXPIRE_MINUTES:-120}
      MAIL_VERIFICATION_SECRET: ${MAIL_VERIFICATION_SECRET:-}
      MAIL_VERIFICATION_EXPIRE_MINUTES: ${MAIL_VERIFICATION_EXPIRE_MINUTES:-10}
      MAIL_VERIFICATION_MAX_ATTEMPTS: ${MAIL_VERIFICATION_MAX_ATTEMPTS:-2}
      APPRISE_URL: ${APPRISE_URL:-}
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID:-}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET:-}
      STRAVA_REDIRECT_URI: ${STRAVA_REDIRECT_URI:-}
      STRAVA_SCOPES: ${STRAVA_SCOPES:-read,activity:read_all}
      STRAVA_TOKENS_FILE: ${STRAVA_TOKENS_FILE:-.strava_tokens.json}
    volumes:
      - ./DB/rides:/opt/tfe/DB/rides
    ports:
      - "8000:8000"

volumes:
  postgres_data:
